defmodule CardVault.Model.Item do
  defstruct [
    :description,
    :price,
    :image_url
  ]

  def create(description, price) do
    item = %CardVault.Model.Item{
      description: description,
      price: price,
      image_url: description_to_image()[description]
    }

    {:ok, item}
    |> validates_description
  end

  defp description_to_image() do
    %{
      "A Bowl of Craft Dinner" => "Ic_item_kraft_dinner.png",
      "Mr. Twig" => "Ic_item_mr_twig.png",
      "Afghani Goat" => "Ic_item_afghani_goat.png",
      "Alabama Man" => "Ic_item_alabama_man.png",
      "Antonio Banderas Love Doll" => "Ic_item_antioniobanderes.png",
      "Asses of Fire 2 poster" => "Ic_item_assesoffire.png",
      "Baby Fark McGee-zaxs Broken Pistol" => "Ic_item_brkn_ray_gun.png",
      "Backdoor Tickler" => "Ic_item_anal_tickler.png",
      "Barry Bonds Bat" => "Ic_item_bat.png",
      "Bass Guitar" => "Ic_item_bass_guitar.png",
      "Battered Shield" => "Ic_item_kk_shield.png",
      "BFF Necklace" => "Ic_item_bff.png",
      "Big Mamba Condoms" => "Ic_item_big_mambas.png",
      "Biggest Douche Award" => "Ic_item_douche_award.png",
      "Blob of Stem Cells" => "Ic_item_blob_stemcell.png",
      "Bottle Cap" => "Ic_item_bottle_cap.png",
      "Bottle of Sunscreen" => "Ic_item_ging_sunscrn.png",
      "Bowling Trophy" => "Ic_item_bowling_trophy.png",
      "Boy Band Photo" => "Ic_item_boyband_picture.png",
      "Boy-sized Leash" => "Ic_item_leash_young_boy.png",
      "Brad Pitt Survival Gear Kit" => "Ic_item_brad_survival.png",
      "Broken Bottle" => "Ic_item_brk_bottle.png",
      "Broken Chain" => "Ic_junk_clyde_chain.png",
      "Broken Gnome Pick" => "Ic_item_broken_pick.png",
      "Broken Sword Hilt" => "Ic_item_brkn_hilt.png",
      "Bruce Vilanch Headshot" => "Ic_item_bruce_photo.png",
      "Butters Creamy Goo" => "Ic_item_butters_goo.png",
      "Cafeteria Fraiche" => "Ic_item_creame_fraiche.png",
      "Calculator" => "Ic_item_calculator.png",
      "Canadian Adoption Papers" => "Ic_item_canadian_adoption.png",
      "Canadian Gemstone" => "Ic_item_can_gem.png",
      "Canadian Treasure" => "Ic_item_can_treasure.png",
      "Cardboard Roll" => "Ic_item_worn_scabbard.png",
      "Ceramic Shard" => "Ic_item_ceramic_shard.png",
      "Charm Bracelet" => "Ic_item_chrm_bracelet.png",
      "Cherokee Hair Tampon" => "Ic_item_hair_tampon.png",
      "Chicken Bones" => "Ic_item_foul_femurs.png",
      "Cloth Fragment" => "Ic_item_cloth_fragment.png",
      "Clydes Rulebook" => "Ic_junk_clyde_rulebook.png",
      "Coon Poster" => "Ic_item_coon_poster.png",
      "Crack Pipe" => "Ic_item_crack_pipe.png",
      "Crank Prank Time Phone" => "Ic_item_crank_prank.png",
      "Crumpled Lantern" => "Ic_item_crump_lantern.png",
      "Crumpled Paper" => "Ic_item_crumbled_paper.png",
      "Cyborg Bill Action Figure" => "Ic_item_cyborg_bill.png",
      "Destroyed Laser Pistol" => "Ic_item_brkn_ray_gun.png",
      "Dire Claw" => "Ic_item_d_claw.png",
      "Dire Heart" => "Ic_item_d_heart.png",
      "Dire Scale" => "Ic_item_d_scale.png",
      "DMV Literature" => "Ic_item_dmv_literature.png",
      "Dreidel" => "Ic_item_dreidel.png",
      "Elf Ear" => "Ic_item_elf_ear.png",
      "Empty Glue Bottle" => "Ic_item_glue.png",
      "Faith +1 CD" => "Ic_item_faith_one.png",
      "Fatty Doo Doo DVD" => "Ic_item_fatty_doo.png",
      "Fish Sticks" => "Ic_item_fishsticks.png",
      "Five-Fingered Fister" => "Ic_item_five_fister.png",
      "Fork" => "Ic_item_fork.png",
      "Fractured Bulb" => "Ic_item_brkn_bulb.png",
      "Fractured Slingshot" => "Ic_item_kk_slingshot.png",
      "Girls List" => "Ic_item_girl_list.png",
      "Glass Shard" => "Ic_item_glass_shard.png",
      "Glowing Crystal Fragment" => "Ic_item_brkn_crystal.png",
      "Glowing Goo" => "Ic_item_glowing_goo.png",
      "Gnome Teeth" => "Ic_item_gnometeeth.png",
      "GSM Button" => "Ic_item_ging_btn.png",
      "Guinea Pig Costume" => "Ic_item_guinea_costume.png",
      "Guzungas Gentlemans Magazine" => "Ic_item_gazungas.png",
      "Hawaiian ID Card" => "Ic_item_hawaii_id.png",
      "Head of the Powell Statue" => "Ic_item_head_of_powell_statue.png",
      "Highlighter" => "Ic_item_highlighter.png",
      "Honey Boo Boos Pig Heart" => "Ic_item_pig_heart.png",
      "Ice Cream" => "Ic_item_ice_cream.png",
      "Ikes Chewing Tobacco" => "Ic_item_ike_tobacco.png",
      "Ikes Love Drawing" => "Ic_item_ike_love_drawing.png",
      "Inspector Butters Badge" => "Ic_item_inspec_butters.png",
      "Intellilink Manual" => "Ic_item_intellilink.png",
      "Jack Rabbit" => "Ic_item_jack_rabbit.png",
      "Jew Scout Guide" => "Ic_item_scout_guide.png",
      "Jump Rope" => "Ic_item_kk_jumprope.webp",
      "Lil Crime Stopper Badges" => "Ic_item_jr_dectives.png",
      "Lil Minis Condoms" => "Ic_item_lil_minis.png",
      "Lion King DVD" => "Ic_item_lion_king.png",
      "Macaroni Pictures" => "Ic_item_macaroni_pic.png",
      "Mahalo Rewards Card" => "Ic_item_mahalo_rewards.png",
      "Maple Leaf" => "Ic_item_m_leaf.png",
      "Marker" => "Ic_item_maker1.png",
      "Medical Marijuana Card" => "Ic_item_medical_weed_card.png",
      "Metrosexual Hair Gel" => "Ic_item_hair_gel.png",
      "Microchip" => "Ic_item_microchip.png",
      "Mr. Hankey Construction Set" => "Ic_item_construction_set.png",
      "Mr. Mackeys Coffee Mug" => "Ic_item_mackey_mug.png",
      "Mysterion Picture" => "Ic_item_mysterion_pic.png",
      "NAMBLA Calendar" => "Ic_item_nambla_cal.png",
      "NASCAR Members Club ID" => "Ic_item_nascar_id.png",
      "Needle-sharp Dire Fang" => "Ic_item_d_fang.png",
      "Needle-sharp Fang" => "Ic_item_fang.png",
      "No. 2 Pencil" => "Ic_item_pencil.png",
      "Okama Gamesphere" => "Ic_item_okama_gamesphere.png",
      "Old Baseball Glove" => "Ic_item_old_bball_glove.png",
      "Old Sponge" => "Ic_item_old_sponge.png",
      "Packet of Sea People" => "Ic_item_sea_people.png",
      "Penis Composite Sketch" => "Ic_item_penis_sketch.webp",
      "Phil Collins Oscar" => "Ic_item_phil_collins_oscar.png",
      "Philip Action Figure" => "Ic_item_phillip_doll.png",
      "Picture of Mr. Adlers Fiance" => "Ic_item_fiance.png",
      "Picture of Nichole" => "Ic_item_nichole_pic.png",
      "Picture of Wendy" => "Ic_item_wendy_pic.png",
      "Pile of Splinters" => "Ic_item_pile_splinters.png",
      "Pinewood Derby Car" => "Ic_item_toy_car.png",
      "Pixelated Shard" => "Ic_item_shard.png",
      "Popcorn Necklaces" => "Ic_item_popcorn_necklace.png",
      "Positive Queefy Sore Test" => "Ic_item_queefy_sore_relief.png",
      "Pubes" => "Ic_item_pubes.png",
      "Purity Ring" => "Ic_item_purity_ring.png",
      "Raisins Girl Picture" => "Ic_item_lexus_pic.png",
      "Randy DUI Record" => "Ic_item_breathalyzer.png",
      "Reach For The Skyler CD" => "Ic_item_reach_for_skyler.png",
      "Rectal Photography Kit" => "Ic_item_rectl_camera.png",
      "Ripped Boot" => "Ic_item_gnomeshoe.png",
      "Roll of Tin Foil" => "Ic_item_tinfoil.png",
      "Rusty Pipe" => "Ic_item_rusty_pipe.png",
      "Safety Scissors" => "Ic_item_scissors.png",
      "Sarcastaball Trophy" => "Ic_item_sarcastiball.png",
      "School Book" => "Ic_item_school_book.png",
      "Screwdriver" => "Ic_item_screwdriver.png",
      "Sea-Man Action Figure" => "Ic_item_sea_man.png",
      "Shattered Arrow" => "Ic_item_brkn_arrow.png",
      "Shattered Scimitar Blade" => "Ic_item_scimitar_blade.png",
      "Shredded Plastic" => "Ic_item_shreaded_plastic.png",
      "Small Locket" => "Ic_item_locket.png",
      "Small Paw" => "Ic_item_smallpaw.png",
      "Smores Schnapps" => "Ic_item_smore_schnapps.png",
      "Soap on a Rope" => "Ic_item_soap_rope.png",
      "Space Cash" => "Ic_item_space_cash.png",
      "Sparkeys Leash" => "Ic_item_sparky_leash.png",
      "Spider Limb" => "Ic_item_spider_limb.png",
      "Spiked Wristband" => "Ic_junk_clyde_spike_band.png",
      "Spoiled City Sushi" => "Ic_item_city_sushi.png",
      "Spoiled Clamato Juice" => "Ic_junk_vamps_blood.png",
      "Spoiled Royal Pudding" => "Ic_item_royal_pudding.png",
      "Spoon" => "Ic_item_spoon.png",
      "Squished Eyeball" => "Ic_item_squished_eye.png",
      "St. Peter" => "Ic_item_st_peter.png",
      "STANground Scause" => "Ic_item_stanground.png",
      "Strange Tamer" => "Ic_item_strange_tamer.png",
      "Striped Straw" => "Ic_item_straw.png",
      "Stupid Spoiled Whore Doll" => "Ic_item_ssw_doll.png",
      "Sunbrella" => "Ic_item_sunbrella.png",
      "Sunshine Sparkle Stickers" => "Ic_item_sparkle_stickers.png",
      "Super Phun Thyme Tickets" => "Super_fun_Time.png",
      "Tap Shoes" => "Ic_item_tap_shoes.png",
      "Terrance Action Figure" => "Ic_item_terrance_doll.png",
      "The Poop that Took a Pee" => "Ic_item_poop_book.png",
      "The Spirit of Christmas Film Reel" => "Ic_item_spirit_of_xmas.png",
      "The Sword of a Thousand Truths" => "Ic_item_sword_truths.png",
      "Toilet Paper" => "Ic_item_toiletpaper.png",
      "Torn Bed Sheet" => "Ic_item_kk_bedsheet.png",
      "Torn Cloak Fragment" => "Ic_item_piece_of_elf_cloak.png",
      "Torn Condom" => "Ic_item_brk_condom.png",
      "Torn Underpants" => "Ic_item_torn_underpants.png",
      "Toy Car" => "Ic_item_toy_car.png",
      "Toy Horse" => "Ic_item_toy_horse.png",
      "Toy Truck" => "Ic_item_toy_truck.png",
      "Tuft of Fur" => "Ic_item_tuft_fur.png",
      "Turd Sandwich Ballot" => "Ic_item_turd_ballot.png",
      "TV Award" => "Ic_item_tv_award.png",
      "Urinal Deuce" => "Ic_item_urinal_deuce.png",
      "USB Drive" => "Ic_item_usb.png",
      "Used Firework" => "Ic_item_used_firework.png",
      "VHS Backdoor Sluts 9" => "Ic_item_backdoor_sluts9_VHS.png",
      "VHS What Are These Changes? VHS" => "Ic_item_what_changes_VHS.png",
      "VHS White Trash In Trouble VHS" => "Ic_item_white_trash_VHS.png",
      "Video Game" => "Ic_item_shadow_of_cyclopsus.png",
      "Wad of Web" => "Ic_item_web_wad.png",
      "Well-shined Boots" => "Ic_item_boots.png",
      "What Happened To My School" => "Ic_item_what_happened.png",
      "Wild Wacky Action Bike" => "Ic_item_action_bike.png",
      "Wing CD" => "Ic_item_wing_cd.png"
    }
  end

  defp validates_description({:ok, %{description: description}} = item) do
    validate(
      item,
      description,
      ~r/\A[a-zA-Z0-9\?\'\+\-\.\s]{3,}+\z/i,
      "Invalid description: #{description}",
      "description is empty"
    )
  end

  defp validates_description(error), do: error

  defp validate(_item, nil, _regex, _invalid_message, empty_message), do: {:error, empty_message}

  defp validate(item, field, regex, error_message, _empty_message) do
    if String.match?(field, regex) do
      item
    else
      {:error, error_message}
    end
  end
end
